#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=1:30:00
#PBS -N app-warp-standard-label-rois
#PBS -l vmem=20gb
#PBS -V

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# warp labels
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.5.0 ./warp-labels.sh
